# Generated by Django 4.1.2 on 2022-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_images_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='puan',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
