# Generated by Django 4.1.2 on 2022-10-27 12:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
