# Generated by Django 4.1.2 on 2022-10-27 14:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
